Repository fictadvisor/fictadvisor, pull requests merged in 2024-03, with the labels that each got.

#100 feature #79: created an admin roles flow
  fictadvisor-api/src/v2/api/controllers/RoleController.ts
  fictadvisor-api/src/v2/api/dtos/CreateRoleDTO.ts
  fictadvisor-api/src/v2/api/dtos/SortQARParam.ts
  fictadvisor-api/src/v2/api/dtos/UpdateRoleDTO.ts
  fictadvisor-api/src/v2/database/entities/DbRole.ts
  fictadvisor-web/src/app/admin/roles/create/page.tsx
  fictadvisor-web/src/app/admin/roles/edit/[roleId]/page.tsx
  fictadvisor-web/src/app/admin/roles/page.tsx
  fictadvisor-web/src/components/pages/admin/admin-roles/common/constants/Options.ts
  fictadvisor-web/src/components/pages/admin/admin-roles/common/constants/RolesInitialValues.ts
  fictadvisor-web/src/components/pages/admin/admin-roles/common/constants/RolesSearchConstants.ts
  fictadvisor-web/src/components/pages/admin/admin-roles/common/types/HeaderRolesSearch.ts
  fictadvisor-web/src/components/pages/admin/admin-roles/create-roles-page/AdminRolesCreate.styles.ts
  fictadvisor-web/src/components/pages/admin/admin-roles/create-roles-page/AdminRolesCreate.tsx
  fictadvisor-web/src/components/pages/admin/admin-roles/create-roles-page/index.ts
  fictadvisor-web/src/components/pages/admin/admin-roles/edit-roles-page/EditRolesPage.styles.ts
  fictadvisor-web/src/components/pages/admin/admin-roles/edit-roles-page/EditRolesPage.tsx
  fictadvisor-web/src/components/pages/admin/admin-roles/edit-roles-page/index.ts
  fictadvisor-web/src/components/pages/admin/admin-roles/search-roles-page/AdminRolesSearch.styles.ts
  fictadvisor-web/src/components/pages/admin/admin-roles/search-roles-page/AdminRolesSearch.tsx
  fictadvisor-web/src/components/pages/admin/admin-roles/search-roles-page/components/header-roles-search/HeaderRolesSearch.styles.ts
  fictadvisor-web/src/components/pages/admin/admin-roles/search-roles-page/components/header-roles-search/HeaderRolesSearch.tsx
  fictadvisor-web/src/components/pages/admin/admin-roles/search-roles-page/components/header-roles-search/index.ts
  fictadvisor-web/src/components/pages/admin/admin-roles/search-roles-page/components/roles-list/RolesList.styles.ts
  fictadvisor-web/src/components/pages/admin/admin-roles/search-roles-page/components/roles-list/RolesList.tsx
  fictadvisor-web/src/components/pages/admin/admin-roles/search-roles-page/components/roles-list/index.ts
  fictadvisor-web/src/components/pages/admin/admin-roles/search-roles-page/index.ts
  fictadvisor-web/src/lib/api/role/RoleAPI.ts
  fictadvisor-web/src/lib/api/role/types/CreateRoleBody.ts
  fictadvisor-web/src/lib/api/role/types/GetAllResponse.ts
  fictadvisor-web/src/types/role.ts
Labels: feature, back

#284 feature #36: created a discipline flow
  fictadvisor-web/src/app/admin/disciplines/create/page.tsx
  fictadvisor-web/src/app/admin/disciplines/edit/[disciplineId]/page.tsx
  fictadvisor-web/src/app/admin/disciplines/page.tsx
  fictadvisor-web/src/components/pages/admin/disciplines-admin-page/DisciplinesAdminPage.styles.ts
  fictadvisor-web/src/components/pages/admin/disciplines-admin-page/DisciplinesAdminPage.tsx
  fictadvisor-web/src/components/pages/admin/disciplines-admin-page/components/disciplines-admin-search/DisciplinesAdminSearch.styles.ts
  fictadvisor-web/src/components/pages/admin/disciplines-admin-page/components/disciplines-admin-search/DisciplinesAdminSearch.tsx
  fictadvisor-web/src/components/pages/admin/disciplines-admin-page/components/disciplines-admin-search/constants/index.ts
  fictadvisor-web/src/components/pages/admin/disciplines-admin-page/components/disciplines-admin-search/index.ts
  fictadvisor-web/src/components/pages/admin/disciplines-admin-page/components/disciplines-admin-search/types/index.ts
  fictadvisor-web/src/components/pages/admin/disciplines-admin-page/components/disciplines-table/DisciplinesTable.styles.ts
  fictadvisor-web/src/components/pages/admin/disciplines-admin-page/components/disciplines-table/DisciplinesTable.tsx
  fictadvisor-web/src/components/pages/admin/disciplines-admin-page/components/disciplines-table/index.ts
  fictadvisor-web/src/components/pages/admin/disciplines-admin-page/index.ts
  fictadvisor-web/src/components/pages/admin/disciplines-admin-page/pages/disciplines-create-page/DisciplinesAdminCreatePage.styles.ts
  fictadvisor-web/src/components/pages/admin/disciplines-admin-page/pages/disciplines-create-page/DisciplinesAdminCreatePage.tsx
  fictadvisor-web/src/components/pages/admin/disciplines-admin-page/pages/disciplines-create-page/index.ts
  fictadvisor-web/src/components/pages/admin/disciplines-admin-page/pages/disciplines-edit-page/DisciplinesAdminEditPage.tsx
  fictadvisor-web/src/components/pages/admin/disciplines-admin-page/pages/disciplines-edit-page/DisciplinesAdminPage.styles.ts
  fictadvisor-web/src/components/pages/admin/disciplines-admin-page/pages/disciplines-edit-page/components/disciplines-info-section/DisciplinesInfoSection.styles.ts
  fictadvisor-web/src/components/pages/admin/disciplines-admin-page/pages/disciplines-edit-page/components/disciplines-info-section/DisciplinesInfoSection.tsx
  fictadvisor-web/src/components/pages/admin/disciplines-admin-page/pages/disciplines-edit-page/components/disciplines-info-section/index.ts
  fictadvisor-web/src/components/pages/admin/disciplines-admin-page/pages/disciplines-edit-page/index.ts
  fictadvisor-web/src/lib/api/discipline/DisciplineAPI.ts
  fictadvisor-web/src/lib/api/discipline/types/AddDiscipline.ts
  fictadvisor-web/src/lib/api/discipline/types/AddDisciplineTeacher.ts
  fictadvisor-web/src/lib/api/discipline/types/GetAllDisciplineTeachers.ts
  fictadvisor-web/src/lib/api/discipline/types/GetAllDisciplines.ts
  fictadvisor-web/src/lib/api/discipline/types/UpdateDisciplineTeacher.ts
  fictadvisor-web/src/types/discipline.ts
Labels: feature, front

#285 bugfix #271: fixed bugs on teacher admin page
  fictadvisor-web/src/components/pages/admin/admin-teachers/common/components/teacher-personal-inputs/TeacherPersonalInputs.styles.ts
  fictadvisor-web/src/components/pages/admin/admin-teachers/common/components/teacher-personal-inputs/TeacherPersonalInputs.tsx
  fictadvisor-web/src/components/pages/admin/admin-teachers/common/components/teacher-personal-inputs/components/change-avatar-window/ChangeAvatar.styles.ts
  fictadvisor-web/src/components/pages/admin/admin-teachers/common/components/teacher-personal-inputs/components/change-avatar-window/ChangeAvatar.tsx
  fictadvisor-web/src/components/pages/admin/admin-teachers/common/components/teacher-personal-inputs/components/change-avatar-window/components/avatar-dropzone/AvatarDropzone.styles.ts
  fictadvisor-web/src/components/pages/admin/admin-teachers/common/components/teacher-personal-inputs/components/change-avatar-window/components/avatar-dropzone/AvatarDropzone.tsx
  fictadvisor-web/src/components/pages/admin/admin-teachers/common/components/teacher-personal-inputs/components/change-avatar-window/components/avatar-dropzone/index.ts
  fictadvisor-web/src/components/pages/admin/admin-teachers/common/components/teacher-personal-inputs/components/change-avatar-window/components/avatar-dropzone/utils/handleFileSelect.ts
  fictadvisor-web/src/components/pages/admin/admin-teachers/common/components/teacher-personal-inputs/components/change-avatar-window/index.ts
  fictadvisor-web/src/components/pages/admin/admin-teachers/create-teacher-admin-page/components/header-create/HeaderCreate.tsx
  fictadvisor-web/src/components/pages/admin/admin-teachers/create-teacher-admin-page/types/index.ts
  fictadvisor-web/src/components/pages/admin/admin-teachers/edit-teachers-admin-page/TeachersAdminEditPage.tsx
  fictadvisor-web/src/components/pages/admin/admin-teachers/edit-teachers-admin-page/components/edit-teacher-comments/components/comment-text-area/CommentTextArea.styles.ts
  fictadvisor-web/src/components/pages/admin/admin-teachers/edit-teachers-admin-page/components/header-edit/HeaderEdit.tsx
Labels: bug, front

#286 bug #24: null value teacher is accepted
  fictadvisor-web/src/components/pages/schedule-page/SchedulePage.tsx
  fictadvisor-web/src/components/pages/schedule-page/schedule-event-edit-section/schedule-form/validation/index.ts
Labels: bug, front

#162 feature #75: added html to mail messages
  fictadvisor-api/email/templates/template.hbs
  fictadvisor-api/src/v2/api/services/AuthService.ts
Labels: front, back

#295 migration #294 Rename icon column on resource table
  fictadvisor-api/prisma/migrations/20240319162757_rename_icon_colum_for_student_resource/migration.sql
  fictadvisor-api/prisma/schema.prisma
  fictadvisor-api/src/v2/api/datas/CreateResourceData.ts
  fictadvisor-api/src/v2/api/datas/UpdateResourceData.ts
  fictadvisor-api/src/v2/api/dtos/CreateResourceDTO.ts
  fictadvisor-api/src/v2/database/repositories/ResourceRepository.ts
Labels: migration, back

#282 enhancement #281: updated poll endpoints for telegram
  fictadvisor-api/src/v2/api/controllers/DisciplineTeacherController.ts
  fictadvisor-api/src/v2/api/controllers/PollController.ts
  fictadvisor-api/src/v2/api/dtos/CreateAnswersDTO.ts
  fictadvisor-api/src/v2/api/responses/DisciplineTeacherQuestionsResponse.ts
  fictadvisor-api/src/v2/api/services/DisciplineTeacherService.ts
  fictadvisor-api/src/v2/modules/AccessModule.ts
Labels: enhancement, back

#301 design #292: updated fictadvisor logo
  fictadvisor-web/public/icons/logo.svg
Labels: design

#293 bug #23: other event fields are not visible
  fictadvisor-web/src/components/pages/schedule-page/schedule-event-edit-section/schedule-form/ScheduleEventForm.tsx
  fictadvisor-web/src/components/pages/schedule-page/schedule-event-edit-section/schedule-form/constants/index.ts
  fictadvisor-web/src/components/pages/schedule-page/schedule-event-edit-section/schedule-form/validation/index.ts
  fictadvisor-web/src/components/pages/schedule-page/schedule-event-edit-section/schedule-info-card/ScheduleInfoCard.tsx
Labels: bug, front

#92 feature #85: create an admin grants flow
  fictadvisor-api/src/v2/api/controllers/AdmissionController.ts
  fictadvisor-api/src/v2/api/controllers/GrantController.ts
  fictadvisor-api/src/v2/api/controllers/RoleController.ts
  fictadvisor-api/src/v2/api/dtos/CreateGrantDTO.ts
  fictadvisor-api/src/v2/api/dtos/CreateRoleWithGrantsDTO.ts
  fictadvisor-api/src/v2/api/dtos/QueryAllGrantsDTO.ts
  fictadvisor-api/src/v2/api/dtos/QueryAllGroupDTO.ts
  fictadvisor-api/src/v2/api/dtos/UpdateGrantDTO.ts
  fictadvisor-api/src/v2/api/responses/GrantsResponse.ts
  fictadvisor-api/src/v2/api/services/GrantService.ts
  fictadvisor-api/src/v2/api/services/RoleService.ts
  fictadvisor-api/src/v2/modules/UserModule.ts
  fictadvisor-api/src/v2/security/PERMISSION.ts
  fictadvisor-api/src/v2/utils/ArrayUtil.ts
  fictadvisor-web/src/app/admin/roles/[roleId]/grants/create/page.tsx
  fictadvisor-web/src/app/admin/roles/[roleId]/grants/edit/[grantId]/page.tsx
  fictadvisor-web/src/app/admin/roles/[roleId]/grants/page.tsx
  fictadvisor-web/src/components/pages/admin/admin-grants/common/constants/GrantsInitialValues.ts
  fictadvisor-web/src/components/pages/admin/admin-grants/common/constants/Options.ts
  fictadvisor-web/src/components/pages/admin/admin-grants/common/types/GrantsSearchFormFields.ts
  fictadvisor-web/src/components/pages/admin/admin-grants/common/types/index.ts
  fictadvisor-web/src/components/pages/admin/admin-grants/create-grants-page/AdminGrantsCreate.styles.ts
  fictadvisor-web/src/components/pages/admin/admin-grants/create-grants-page/AdminGrantsCreate.tsx
  fictadvisor-web/src/components/pages/admin/admin-grants/create-grants-page/index.ts
  fictadvisor-web/src/components/pages/admin/admin-grants/edit-grants-page/EditGrantsPage.styles.ts
  fictadvisor-web/src/components/pages/admin/admin-grants/edit-grants-page/EditGrantsPage.tsx
  fictadvisor-web/src/components/pages/admin/admin-grants/edit-grants-page/index.ts
  fictadvisor-web/src/components/pages/admin/admin-grants/search-grants-page/AdminGrantsSearch.styles.ts
  fictadvisor-web/src/components/pages/admin/admin-grants/search-grants-page/AdminGrantsSearch.tsx
  fictadvisor-web/src/components/pages/admin/admin-grants/search-grants-page/components/grants-list/GrantsList.styles.ts
  fictadvisor-web/src/components/pages/admin/admin-grants/search-grants-page/components/grants-list/GrantsList.tsx
  fictadvisor-web/src/components/pages/admin/admin-grants/search-grants-page/components/grants-list/index.ts
  fictadvisor-web/src/components/pages/admin/admin-grants/search-grants-page/components/header-grants-search/HeaderGrantsSearch.styles.ts
  fictadvisor-web/src/components/pages/admin/admin-grants/search-grants-page/components/header-grants-search/HeaderGrantsSearch.tsx
  fictadvisor-web/src/components/pages/admin/admin-grants/search-grants-page/components/header-grants-search/index.ts
  fictadvisor-web/src/components/pages/admin/admin-grants/search-grants-page/index.ts
  fictadvisor-web/src/components/pages/admin/admin-roles/edit-roles-page/EditRolesPage.tsx
  fictadvisor-web/src/components/pages/admin/admin-roles/search-roles-page/components/roles-list/RolesList.tsx
  fictadvisor-web/src/lib/api/grants/GrantsAPI.ts
  fictadvisor-web/src/lib/api/grants/types/CreateGrantBody.ts
  fictadvisor-web/src/lib/api/grants/types/GetAllGrantsResponse.ts
  fictadvisor-web/src/lib/api/role/RoleAPI.ts
Labels: feature, front, back

#205 feature #108: create an admin main page flow
  fictadvisor-api/src/v2/api/ApiModule.ts
  fictadvisor-api/src/v2/api/controllers/PageTextController.ts
  fictadvisor-api/src/v2/api/controllers/ResourceController.ts
  fictadvisor-api/src/v2/api/dtos/CreatePageTextDTO.ts
  fictadvisor-api/src/v2/api/dtos/CreateResourceDTO.ts
  fictadvisor-api/src/v2/api/dtos/QueryAllPageTextsDTO.ts
  fictadvisor-api/src/v2/api/dtos/QueryAllResourcesDTO.ts
  fictadvisor-api/src/v2/api/dtos/UpdatePageTextsDTO.ts
  fictadvisor-api/src/v2/api/dtos/UpdateResourceDTO.ts
  fictadvisor-api/src/v2/api/dtos/UpdateResourcesDTO.ts
  fictadvisor-api/src/v2/api/pipes/ResourceByIdPipe.ts
  fictadvisor-api/src/v2/api/responses/PageTextResponse.ts
  fictadvisor-api/src/v2/api/responses/PageTextsResponse.ts
  fictadvisor-api/src/v2/api/responses/ResourceResponse.ts
  fictadvisor-api/src/v2/api/responses/ResourcesResponse.ts
  fictadvisor-api/src/v2/api/services/PageTextService.ts
  fictadvisor-api/src/v2/api/services/ResourceService.ts
  fictadvisor-api/src/v2/database/repositories/PageTextRepository.ts
  fictadvisor-api/src/v2/database/repositories/ResourceRepository.ts
  fictadvisor-api/src/v2/mappers/ResourceMapper.ts
  fictadvisor-api/src/v2/modules/MapperModule.ts
  fictadvisor-api/src/v2/modules/PageTextModule.ts
  fictadvisor-api/src/v2/modules/PrismaModule.ts
  fictadvisor-api/src/v2/modules/ResourceModule.ts
  fictadvisor-api/src/v2/security/PERMISSION.ts
  fictadvisor-web/src/app/admin/main/page.tsx
  fictadvisor-web/src/components/common/layout/admin-panel/AdminPanel.tsx
  fictadvisor-web/src/components/common/layout/admin-panel/constants/index.tsx
  fictadvisor-web/src/components/common/ui/form/switch/Switch.tsx
  fictadvisor-web/src/components/pages/admin/admin-main/AdminHomePage.styles.ts
  fictadvisor-web/src/components/pages/admin/admin-main/AdminHomePage.tsx
  fictadvisor-web/src/components/pages/admin/admin-main/components/page-texts-form/PageTextsForm.styles.ts
  fictadvisor-web/src/components/pages/admin/admin-main/components/page-texts-form/PageTextsForm.tsx
  fictadvisor-web/src/components/pages/admin/admin-main/components/page-texts-form/index.ts
  fictadvisor-web/src/components/pages/admin/admin-main/components/page-texts-form/types/PageTextsInterfaces.ts
  fictadvisor-web/src/components/pages/admin/admin-main/components/student-resources-form/StudentResourcesForm.styles.ts
  fictadvisor-web/src/components/pages/admin/admin-main/components/student-resources-form/StudentResourcesForm.tsx
  fictadvisor-web/src/components/pages/admin/admin-main/components/student-resources-form/index.ts
  fictadvisor-web/src/components/pages/admin/admin-main/index.ts
  fictadvisor-web/src/components/pages/main-page/MainPage.tsx
  fictadvisor-web/src/lib/api/page-texts/PageTextsAPI.ts
  fictadvisor-web/src/lib/api/page-texts/types/GetPageTextsResponse.ts
  fictadvisor-web/src/lib/api/student-resources/StudentResourcesAPI.ts
  fictadvisor-web/src/lib/api/student-resources/types/GetStudentResourcesResponse.ts
  fictadvisor-web/src/lib/services/permisson/types/index.ts
Labels: feature, front, back

#283 bug #248: made permissions global for FE and BE
  .dockerignore
  .github/workflows/build-back.yml
  .github/workflows/build-front.yml
  .github/workflows/deploy-back.yml
  .github/workflows/deploy-front.yml
  .gitignore
  fictadvisor-api/Dockerfile
  fictadvisor-api/package.json
  fictadvisor-api/src/main.ts
  fictadvisor-api/src/v2/api/controllers/CathedraController.ts
  fictadvisor-api/src/v2/api/controllers/DisciplineController.ts
  fictadvisor-api/src/v2/api/controllers/DisciplineTeacherController.ts
  fictadvisor-api/src/v2/api/controllers/EntrantController.ts
  fictadvisor-api/src/v2/api/controllers/GrantController.ts
  fictadvisor-api/src/v2/api/controllers/GroupController.ts
  fictadvisor-api/src/v2/api/controllers/PageTextController.ts
  fictadvisor-api/src/v2/api/controllers/PollController.ts
  fictadvisor-api/src/v2/api/controllers/ResourceController.ts
  fictadvisor-api/src/v2/api/controllers/RoleController.ts
  fictadvisor-api/src/v2/api/controllers/ScheduleController.ts
  fictadvisor-api/src/v2/api/controllers/StudentController.ts
  fictadvisor-api/src/v2/api/controllers/SubjectController.ts
  fictadvisor-api/src/v2/api/controllers/TeacherController.ts
  fictadvisor-api/src/v2/api/controllers/UserController.ts
  fictadvisor-api/src/v2/api/dtos/CheckPermissionsDTO.ts
  fictadvisor-api/src/v2/api/services/PermissionService.ispec.ts
  fictadvisor-api/src/v2/utils/documentation/decorators.ts
  fictadvisor-api/src/v2/utils/files/FileService.ts
  fictadvisor-web/Dockerfile
  fictadvisor-web/next.config.js
  fictadvisor-web/package.json
  fictadvisor-web/src/components/pages/account-page/components/group-tab/GroupTab.tsx
  fictadvisor-web/src/components/pages/account-page/components/group-tab/components/table/student-table/StudentsTable.tsx
  fictadvisor-web/src/components/pages/account-page/components/group-tab/components/table/student-table/components/editing-column/EditingColumn.tsx
  fictadvisor-web/src/components/pages/account-page/components/group-tab/components/table/student-table/components/mobile-dropdown/MobileDropdown.tsx
  fictadvisor-web/src/components/pages/schedule-page/calendar-section/CalendarSection.tsx
  fictadvisor-web/src/components/pages/schedule-page/schedule-event-edit-section/schedule-info-card/ScheduleInfoCard.tsx
  fictadvisor-web/src/lib/services/group/GroupService.ts
  fictadvisor-web/src/lib/services/permisson/types/index.ts
  fictadvisor-web/src/lib/services/permisson/utils/createPermissionRequest.ts
  package.json
  turbo.json
  utils/package.json
  utils/src/index.ts
  utils/src/security/PERMISSION.ts
  utils/src/security/index.ts
  utils/tsconfig.json
Labels: bug, back

#305 enhancement #291: updated brand name
  fictadvisor-web/src/app/(admission)/_contract-admin/page.tsx
  fictadvisor-web/src/app/(admission)/_entrant-admin/page.tsx
  fictadvisor-web/src/app/(admission)/_entrant-dashboard/page.tsx
  fictadvisor-web/src/app/about/page.tsx
  fictadvisor-web/src/app/account/page.tsx
  fictadvisor-web/src/app/login/page.tsx
  fictadvisor-web/src/app/page.tsx
  fictadvisor-web/src/app/poll/page.tsx
  fictadvisor-web/src/app/privacy/page.tsx
  fictadvisor-web/src/app/register/page.tsx
  fictadvisor-web/src/components/pages/login-page/components/login-form-block/LoginFormBlock.tsx
  fictadvisor-web/src/components/pages/login-page/components/logo-register-block/LogoRegisterBlock.tsx
  fictadvisor-web/src/components/pages/main-page/MainPage.tsx
  fictadvisor-web/src/components/pages/main-page/components/resource-card/ResourceCard.tsx
  fictadvisor-web/src/components/pages/privacy-page/PrivacyPage.tsx
  fictadvisor-web/src/components/pages/register/register-page/components/left-block/LeftBlock.tsx
  fictadvisor-web/src/components/pages/register/register-page/components/right-block/RightBlock.tsx
  fictadvisor-web/src/components/pages/schedule-page/SchedulePage.tsx
  fictadvisor-web/src/config/index.ts
Labels: enhancement, front

#309 bug #308: fixed multiple access guard
  fictadvisor-api/src/v2/modules/AccessModule.ts
  fictadvisor-api/src/v2/security/multiple-access-guard/MultipleAccessGuard.ts
  fictadvisor-api/src/v2/utils/documentation/decorators.ts
Labels: bug, back
