Repository fictadvisor/fictadvisor, pull requests merged in 2024-06, with the labels that each got.

#390 enhancement #322: improved layout.tsx
  fictadvisor-web/src/app/layout.tsx
  fictadvisor-web/src/app/page.tsx
Labels: enhancement, front

#351 enhancement #333: added datetime library
  fictadvisor-api/package.json
  fictadvisor-api/src/v2/api/services/ScheduleService.ts
  fictadvisor-api/src/v2/utils/date/DateService.spec.ts
  fictadvisor-api/src/v2/utils/date/DateService.ts
Labels: enhancement, refactoring, back

#393 feature #337: implemented an error page for all routes
  fictadvisor-web/src/app/(main)/error-pages/MainErrorPage.styles.ts
  fictadvisor-web/src/app/error.tsx
Labels: feature

#394 Fixed bug on poll
  fictadvisor-api/src/v2/api/controllers/DisciplineTeacherController.ts
  utils/src/security/PERMISSION.ts
Labels: bug, back
