Repository fictadvisor/fictadvisor, pull requests merged in 2024-09, with the labels that each got.

#480 Removed log in getAllGroupEvents method
  fictadvisor-api/src/v2/api/services/ScheduleService.ts
Labels: refactoring, back

#484 bug #406: fixed cross highlighting on the 'Survey' page
  fictadvisor-web/src/components/common/ui/cards/poll-teacher-card/pollTeachaerCard.styles.ts
Labels: bug

#489 enhancement #485: React Query Devtools
  fictadvisor-web/package.json
  fictadvisor-web/src/components/common/layout/providers/Providers.tsx
  yarn.lock
Labels: enhancement

#478 bug #467: fixed verifyStudent functions
  fictadvisor-api/src/v2/api/services/UserService.ts
  fictadvisor-api/src/v2/utils/files/FileService.ts
Labels: bug, back

#497 enhancement #460: separated swagger doc from implementation
  fictadvisor-api/src/v2/api/controllers/TeacherController.ts
  fictadvisor-api/src/v2/utils/documentation/decorators.ts
  fictadvisor-api/src/v2/utils/documentation/defaultResponses.ts
  fictadvisor-api/src/v2/utils/documentation/teacher/connectCathedra.ts
  fictadvisor-api/src/v2/utils/documentation/teacher/create.ts
  fictadvisor-api/src/v2/utils/documentation/teacher/createContact.ts
  fictadvisor-api/src/v2/utils/documentation/teacher/delete.ts
  fictadvisor-api/src/v2/utils/documentation/teacher/deleteContact.ts
  fictadvisor-api/src/v2/utils/documentation/teacher/disconnectCathedra.ts
  fictadvisor-api/src/v2/utils/documentation/teacher/getAll.ts
  fictadvisor-api/src/v2/utils/documentation/teacher/getAllContacts.ts
  fictadvisor-api/src/v2/utils/documentation/teacher/getComments.ts
  fictadvisor-api/src/v2/utils/documentation/teacher/getContact.ts
  fictadvisor-api/src/v2/utils/documentation/teacher/getDisciplines.ts
  fictadvisor-api/src/v2/utils/documentation/teacher/getMarks.ts
  fictadvisor-api/src/v2/utils/documentation/teacher/getSubject.ts
  fictadvisor-api/src/v2/utils/documentation/teacher/getSubjects.ts
  fictadvisor-api/src/v2/utils/documentation/teacher/getTeacher.ts
  fictadvisor-api/src/v2/utils/documentation/teacher/getTeacherRoles.ts
  fictadvisor-api/src/v2/utils/documentation/teacher/index.ts
  fictadvisor-api/src/v2/utils/documentation/teacher/sendComplaint.ts
  fictadvisor-api/src/v2/utils/documentation/teacher/update.ts
  fictadvisor-api/src/v2/utils/documentation/teacher/updateContact.ts
  utils/src/requests/ResponseQueryDTO.ts
Labels: documentation, back
