Repository fictadvisor/fictadvisor, pull requests merged in 2024-04, with the labels that each got.

#257 refactoring #102: updated roz.kpi.ua parser
  fictadvisor-api/src/v2/utils/date/DateService.ts
  fictadvisor-api/src/v2/utils/parser/CampusParser.ts
  fictadvisor-api/src/v2/utils/parser/GeneralParser.ts
  fictadvisor-api/src/v2/utils/parser/ParserModule.ts
  fictadvisor-api/src/v2/utils/parser/RozParams.ts
  fictadvisor-api/src/v2/utils/parser/RozParser.ts
  fictadvisor-api/src/v2/utils/parser/ScheduleParserTypes.ts
Labels: refactoring, back

#348 feature #2: added service worker
  fictadvisor-web/public/service-worker.js
  fictadvisor-web/src/app/layout.tsx
Labels: feature, front

#357 bugfix #349: Fixed discipline and cathedra endpoints
  fictadvisor-api/src/v2/api/controllers/CathedraController.ts
  fictadvisor-api/src/v2/api/responses/DisciplineTeachersResponse.ts
  fictadvisor-api/src/v2/mappers/DisciplineMapper.ts
Labels: bug, back

#377 bugfix #376: get pagetext needs permission
  fictadvisor-api/src/v2/api/controllers/PageTextController.ts
  utils/src/security/PERMISSION.ts
Labels: bug, back

#381 enhancement #380: make sw for production
  fictadvisor-web/public/service-worker.js
  fictadvisor-web/src/app/layout.tsx
Labels: enhancement, front
