Repository fictadvisor/fictadvisor, pull requests merged in 2024-12, with the labels that each got.

#561 bug #544: fixed buttons absence on group tab
  fictadvisor-web/src/lib/services/group/GroupService.ts
Labels: bug, front

#569 Bug #563: fixed button sort group
  fictadvisor-web/src/lib/api/group/GroupAPI.ts
  fictadvisor-web/src/lib/services/group/GroupService.ts
Labels: bug, front

#574 bug #570: fix teacher list display
  fictadvisor-web/src/app/(main)/(search-pages)/teachers/page.tsx
Labels: bug, front

#495 fix: load offset
  fictadvisor-web/src/components/common/ui/load-page/LoadPage.tsx
Labels: enhancement, front

#575 bug #571: fixed displaying of discipline type icons
  fictadvisor-web/.env.development
  fictadvisor-web/src/app/(main)/(search-pages)/teachers/page.tsx
  fictadvisor-web/src/components/common/ui/cards/card-discipline-types/CardDisciplineTypes.module.scss
  fictadvisor-web/src/components/common/ui/cards/card-discipline-types/CardDisciplineTypes.tsx
Labels: bug, front

#584 bug #583: fixed width for teacher header card
  fictadvisor-web/src/components/common/ui/cards/teacher-header-card/TeacherHeaderCard.styles.ts
Labels: bug, front

#585 enhancement/refactor-search-system
  fictadvisor-api/package.json
  fictadvisor-web/src/app/(main)/(search-pages)/poll/components/poll-search-form/PollSearchForm.tsx
  fictadvisor-web/src/app/(main)/(search-pages)/poll/components/poll-teacher-search-list/PollTeacherSearchList.tsx
  fictadvisor-web/src/app/(main)/(search-pages)/poll/page.tsx
  fictadvisor-web/src/app/(main)/(search-pages)/search-form/SearchForm.tsx
  fictadvisor-web/src/app/(main)/(search-pages)/subjects/page.tsx
  fictadvisor-web/src/app/(main)/(search-pages)/teachers/page.tsx
  fictadvisor-web/src/components/common/ui/breadcrumbs/Breadcrumbs.tsx
  fictadvisor-web/src/components/common/ui/form/dropdown/Dropdown.tsx
  yarn.lock
Labels: refactoring, front
