Repository fictadvisor/fictadvisor, pull requests merged in 2024-01, with the labels that each got.

#45 feature #842: Implemented an endpoint to receive all disciplines
  fictadvisor-api/src/v2/api/controllers/DisciplineController.ts
  fictadvisor-api/src/v2/api/dtos/QueryAllDisciplinesDTO.ts
  fictadvisor-api/src/v2/api/pipes/QueryAllDisciplinesPipe.ts
  fictadvisor-api/src/v2/api/responses/DisciplineResponse.ts
  fictadvisor-api/src/v2/api/responses/TeacherResponse.ts
  fictadvisor-api/src/v2/api/services/DisciplineService.ts
  fictadvisor-api/src/v2/api/services/GroupService.ts
  fictadvisor-api/src/v2/api/services/PollService.ts
  fictadvisor-api/src/v2/api/services/ScheduleService.ts
  fictadvisor-api/src/v2/api/services/UserService.ts
  fictadvisor-api/src/v2/database/repositories/DisciplineRepository.ts
  fictadvisor-api/src/v2/mappers/DisciplineMapper.ts
  fictadvisor-api/src/v2/modules/DisciplineModule.ts
  fictadvisor-api/src/v2/modules/TeacherModule.ts
  fictadvisor-api/src/v2/utils/QueryAllDTO.ts
Labels: feature, back

#46 feature #862: Added the ability to get all users
  fictadvisor-api/src/v2/api/controllers/RoleController.ts
  fictadvisor-api/src/v2/api/controllers/UserController.ts
  fictadvisor-api/src/v2/api/dtos/QueryAllUsersDTO.ts
  fictadvisor-api/src/v2/api/responses/UsersResponse.ts
  fictadvisor-api/src/v2/api/services/UserService.ts
  fictadvisor-api/src/v2/database/repositories/UserRepository.ts
  fictadvisor-api/src/v2/mappers/UserMapper.ts
  fictadvisor-api/src/v2/security/PERMISSION.ts
Labels: feature, back

#81 enhancement #18: ensuring "Сьогодні" button availability
  fictadvisor-web/src/components/pages/schedule-page/schedule-section/components/schedule-header/ScheduleHeader.tsx
Labels: enhancement, front

#44 feature #858: disconnecting teachers from cathedras
  fictadvisor-api/src/v2/api/controllers/TeacherController.ts
  fictadvisor-api/src/v2/api/responses/TeacherWithRolesAndContactsResponse.ts
  fictadvisor-api/src/v2/api/services/TeacherService.ts
  fictadvisor-api/src/v2/security/PERMISSION.ts
Labels: feature, back

#86 documentation #57: updated swagger for groups
  fictadvisor-api/src/v2/api/controllers/GroupController.ts
  yarn.lock
Labels: documentation, back

#90 documentation #58: updated swagger for groups
  fictadvisor-api/src/v2/api/controllers/GroupController.ts
  fictadvisor-api/src/v2/api/dtos/EmailDTO.ts
  fictadvisor-api/src/v2/api/dtos/RoleDTO.ts
Labels: documentation, back

#48 Feature/permission service
  fictadvisor-web/src/components/pages/account-page/components/group-tab/GroupTab.tsx
  fictadvisor-web/src/components/pages/account-page/components/group-tab/components/table/student-table/StudentsTable.tsx
  fictadvisor-web/src/components/pages/account-page/components/group-tab/components/table/student-table/components/EditingColumn.tsx
  fictadvisor-web/src/components/pages/account-page/components/group-tab/components/table/student-table/components/MobileDropdown.tsx
  fictadvisor-web/src/components/pages/account-page/components/group-tab/components/table/types/index.ts
  fictadvisor-web/src/components/pages/schedule-page/calendar-section/CalendarSection.tsx
  fictadvisor-web/src/components/pages/schedule-page/schedule-event-edit-section/schedule-info-card/ScheduleInfoCard.tsx
  fictadvisor-web/src/lib/services/permisson/PermissionService.ts
  fictadvisor-web/src/lib/services/permisson/types/index.ts
  fictadvisor-web/src/lib/services/permisson/utils/createPermissionRequest.ts
  yarn.lock
Labels: front

#88 documentation #56: updated swagger for users
  fictadvisor-api/src/v2/api/controllers/UserController.ts
  fictadvisor-api/src/v2/api/dtos/TelegramDTO.ts
  fictadvisor-api/src/v2/api/responses/RoleWithStudentResponse.ts
  yarn.lock
Labels: documentation, back

#83 feature #82: added ability to delete comments
  fictadvisor-api/src/v2/api/controllers/DisciplineTeacherController.ts
  fictadvisor-api/src/v2/api/dtos/DeleteCommentDTO.ts
  fictadvisor-api/src/v2/api/dtos/UpdateCommentDTO.ts
  fictadvisor-api/src/v2/api/responses/DeleteCommentResponse.ts
  fictadvisor-api/src/v2/api/services/DisciplineTeacherService.ts
  fictadvisor-api/src/v2/database/repositories/QuestionAnswerRepository.ts
  fictadvisor-api/src/v2/security/PERMISSION.ts
Labels: feature, back

#105 bugfix #76: fixed bug with inability to pick selective disciplines
  fictadvisor-api/src/v2/api/services/UserService.ts
Labels: bug, back

#94 bugfix/poll-page-bugs
  fictadvisor-web/src/app/poll/[disciplineTeacherId]/page.tsx
  fictadvisor-web/src/components/common/ui/form/text-area-mui/TextArea.styles.ts
  fictadvisor-web/src/components/pages/poll-page/PollPage.styles.ts
  fictadvisor-web/src/components/pages/poll-page/PollPage.tsx
  fictadvisor-web/src/components/pages/poll-page/components/answers-sheet/AnswerSheet.style.ts
  fictadvisor-web/src/components/pages/poll-page/components/answers-sheet/AnswersSheet.tsx
  fictadvisor-web/src/components/pages/poll-page/components/poll-form/PollForm.styles.ts
  fictadvisor-web/src/components/pages/poll-page/components/poll-form/PollForm.tsx
  fictadvisor-web/src/components/pages/poll-page/components/questions-list/QuestionsList.tsx
  fictadvisor-web/src/components/pages/poll-page/components/single-question/SingleQuestion.tsx
Labels: bug

#111 bugfix/same-poll-answers
  fictadvisor-web/src/components/pages/poll-page/components/answers-sheet/AnswersSheet.tsx
Labels: bug

#41 Feature/create endpoint for user creation
  fictadvisor-api/src/v2/api/controllers/UserController.ts
  fictadvisor-api/src/v2/api/dtos/UserDTO.ts
  fictadvisor-api/src/v2/api/responses/UserResponse.ts
  fictadvisor-api/src/v2/api/services/UserService.ts
  fictadvisor-api/src/v2/security/PERMISSION.ts
Labels: feature, back

#119 enhancement #121: removed svg from teachers page
  fictadvisor-web/src/components/common/ui/radar/Radar.styles.ts
  fictadvisor-web/src/components/common/ui/radar/Radar.tsx
  fictadvisor-web/src/components/common/ui/radar/utils/drawData.ts
  fictadvisor-web/src/components/common/ui/radar/utils/findImage.tsx
  fictadvisor-web/src/components/common/ui/radar/utils/getOptions.ts
  fictadvisor-web/src/components/common/ui/radar/utils/radar-background/11-mobile.tsx
  fictadvisor-web/src/components/common/ui/radar/utils/radar-background/12-mobile.tsx
  fictadvisor-web/src/components/common/ui/radar/utils/radar-background/13-mobile.tsx
  fictadvisor-web/src/components/common/ui/radar/utils/radar-background/15-mobile.tsx
  fictadvisor-web/src/components/common/ui/radar/utils/radar-background/lab-12-desktop.tsx
  fictadvisor-web/src/components/common/ui/radar/utils/radar-background/lect-11-desktop.tsx
  fictadvisor-web/src/components/common/ui/radar/utils/radar-background/lect-lab-13-desktop.tsx
  fictadvisor-web/src/components/common/ui/radar/utils/radar-background/lect-pract-13-desktop.tsx
  fictadvisor-web/src/components/common/ui/radar/utils/radar-background/lect-pract-lab-15-desktop.tsx
  fictadvisor-web/src/components/common/ui/radar/utils/radar-background/pract-12-desktop.tsx
  fictadvisor-web/src/components/pages/personal-teacher-page/personal-teacher-tabs/components/general-tab/GeneralTab.tsx
Labels: feature, front, design

#49 feature #29: added sort button
  fictadvisor-web/src/components/pages/account-page/components/group-tab/GroupTab.styles.ts
  fictadvisor-web/src/components/pages/account-page/components/group-tab/GroupTab.tsx
  fictadvisor-web/src/components/pages/account-page/components/group-tab/components/table/student-table/StudentsTable.styles.ts
  fictadvisor-web/src/components/pages/account-page/components/group-tab/components/table/student-table/StudentsTable.tsx
  fictadvisor-web/src/components/pages/account-page/components/group-tab/components/table/types/index.ts
  fictadvisor-web/src/lib/api/group/GroupAPI.ts
  fictadvisor-web/src/lib/services/group/GroupService.ts
  fictadvisor-web/src/lib/services/group/types/OrderEnum.ts
Labels: front

#131 bugfix/fix-dropdown
  fictadvisor-web/src/components/common/ui/form/checkboxes-dropdown/CheckboxesDropdown.styles.ts
  fictadvisor-web/src/components/common/ui/form/checkboxes-dropdown/CheckboxesDropdown.tsx
  fictadvisor-web/src/components/common/ui/form/checkboxes-dropdown/types/CheckboxesDropdown.ts
Labels: refactoring, front

#104 feature #55: added possibility to leave complaints
  fictadvisor-api/prisma/migrations/20240110134042_add_complaints/migration.sql
  fictadvisor-api/prisma/schema.prisma
  fictadvisor-api/src/v2/api/controllers/TeacherController.ts
  fictadvisor-api/src/v2/api/dtos/ComplaintDTO.ts
  fictadvisor-api/src/v2/api/services/TeacherService.spec.ts
  fictadvisor-api/src/v2/api/services/TeacherService.ts
  fictadvisor-api/src/v2/telegram/TelegramAPI.ts
  fictadvisor-web/src/app/teachers/[teacherId]/page.tsx
  fictadvisor-web/src/components/pages/personal-teacher-page/PersonalTeacherPage.tsx
  fictadvisor-web/src/components/pages/personal-teacher-page/personal-teacher-tabs/PersonalTeacherTabs.styles.ts
  fictadvisor-web/src/components/pages/personal-teacher-page/personal-teacher-tabs/PersonalTeacherTabs.tsx
  fictadvisor-web/src/components/pages/personal-teacher-page/personal-teacher-tabs/components/complaint-popup/ComplaintPopup.styles.ts
  fictadvisor-web/src/components/pages/personal-teacher-page/personal-teacher-tabs/components/complaint-popup/ComplaintPopup.tsx
  fictadvisor-web/src/components/pages/personal-teacher-page/personal-teacher-tabs/components/complaint-popup/components/ComplaintPopupContent.styles.ts
  fictadvisor-web/src/components/pages/personal-teacher-page/personal-teacher-tabs/components/complaint-popup/components/ComplaintPopupContent.tsx
  fictadvisor-web/src/components/pages/personal-teacher-page/personal-teacher-tabs/components/complaint-popup/index.ts
  fictadvisor-web/src/components/pages/personal-teacher-page/personal-teacher-tabs/components/complaint-popup/types/index.ts
  fictadvisor-web/src/components/pages/personal-teacher-page/personal-teacher-tabs/components/complaint-popup/validation/index.ts
  fictadvisor-web/src/lib/api/teacher/TeacherAPI.ts
  fictadvisor-web/src/lib/utils/convertEmptyStringToUndefined.ts
Labels: feature, front, back

#134 feature #52: export group list
  fictadvisor-web/src/components/common/ui/icon-button-mui/variants/ExportButton/ExportButton.stories.ts
  fictadvisor-web/src/components/common/ui/icon-button-mui/variants/ExportButton/ExportButton.styles.ts
  fictadvisor-web/src/components/common/ui/icon-button-mui/variants/ExportButton/ExportButton.tsx
  fictadvisor-web/src/components/pages/account-page/components/group-tab/components/table/student-table/StudentsTable.tsx
  fictadvisor-web/src/lib/api/group/GroupAPI.ts
  fictadvisor-web/src/lib/api/group/types/ExportGroupStudents.ts
Labels: feature, front

#112 feature #54: added leave group on account page
  fictadvisor-api/src/v2/api/services/GroupService.ts
  fictadvisor-web/src/components/pages/account-page/components/group-tab/GroupTab.styles.ts
  fictadvisor-web/src/components/pages/account-page/components/group-tab/GroupTab.tsx
  fictadvisor-web/src/components/pages/schedule-page/calendar-section/CalendarSection.tsx
  fictadvisor-web/src/lib/api/group/GroupAPI.ts
Labels: feature, front, back

#132 design #77: Change role names to icons on mobile teacher's page and teacher searches
  fictadvisor-web/src/components/common/ui/cards/card-roles/CardRoles.module.scss
  fictadvisor-web/src/components/common/ui/cards/card-roles/CardRoles.tsx
  fictadvisor-web/src/components/common/ui/cards/personal-teacher-card/PersonalTeacherCard.tsx
  fictadvisor-web/src/components/common/ui/cards/teacher-card/TeacherCard.styles.ts
  fictadvisor-web/src/components/common/ui/cards/teacher-card/TeacherCard.tsx
  fictadvisor-web/src/components/pages/search-pages/teacher-search/components/TeacherSearchList.tsx
Labels: front, design

#140 feature/transfer-captain-role
  fictadvisor-web/src/components/pages/account-page/components/group-tab/components/table/student-table/StudentsTable.tsx
  fictadvisor-web/src/components/pages/account-page/components/group-tab/components/table/student-table/components/editing-column/EditingColumn.styles.ts
  fictadvisor-web/src/components/pages/account-page/components/group-tab/components/table/student-table/components/editing-column/EditingColumn.tsx
  fictadvisor-web/src/components/pages/account-page/components/group-tab/components/table/student-table/components/editing-column/TransferCaptainPopup.tsx
  fictadvisor-web/src/components/pages/account-page/components/group-tab/components/table/student-table/components/mobile-dropdown/MobileDropdown.style.ts
  fictadvisor-web/src/components/pages/account-page/components/group-tab/components/table/student-table/components/mobile-dropdown/MobileDropdown.tsx
  fictadvisor-web/src/lib/api/group/GroupAPI.ts
  fictadvisor-web/src/lib/api/group/types/UpdateCaptainBody.ts
Labels: feature

#93 enhancement #67: same validation on password
  fictadvisor-api/src/v2/api/controllers/AuthController.ts
  fictadvisor-api/src/v2/api/dtos/LoginDTO.ts
  fictadvisor-api/src/v2/api/dtos/ResetPasswordDTO.ts
  fictadvisor-api/src/v2/api/dtos/UpdatePasswordDTO.ts
  fictadvisor-api/src/v2/api/dtos/UserDTO.ts
  fictadvisor-web/src/components/pages/account-page/components/security-tab/components/change-password-form/ChangePasswordForm.tsx
  fictadvisor-web/src/components/pages/account-page/components/security-tab/components/change-password-form/validation/index.ts
  fictadvisor-web/src/components/pages/password-recovery/create-password-page/components/create-password-form/CreatePasswordForm.tsx
  fictadvisor-web/src/components/pages/password-recovery/create-password-page/components/create-password-form/validation/index.ts
  fictadvisor-web/src/components/pages/register/register-page/components/register-form/validation/index.ts
  fictadvisor-web/src/lib/api/auth/AuthAPI.ts
  fictadvisor-web/src/lib/validation/passwordValidationSchema.ts
Labels: enhancement, front, back

#157 feature #144: fix dropdown #2
  fictadvisor-web/src/components/common/ui/form/checkboxes-dropdown/CheckboxesDropdown.styles.ts
  fictadvisor-web/src/components/common/ui/form/checkboxes-dropdown/CheckboxesDropdown.tsx
  fictadvisor-web/src/components/common/ui/form/checkboxes-dropdown/types/CheckboxesDropdown.ts
Labels: bug, front

#91 documentation #84: updated swagger for teachers
  fictadvisor-api/src/v2/api/controllers/TeacherController.ts
  fictadvisor-api/src/v2/api/pipes/SubjectByIdPipe.ts
  fictadvisor-api/src/v2/api/responses/DisciplineTeacherAndSubjectResponse.ts
  fictadvisor-api/src/v2/api/responses/GroupResponse.ts
  fictadvisor-api/src/v2/api/responses/RoleWithStudentResponse.ts
  fictadvisor-api/src/v2/api/responses/StudentResponse.ts
  fictadvisor-api/src/v2/api/responses/SubjectsResponse.ts
  fictadvisor-api/src/v2/api/responses/TeacherRolesResponse.ts
  fictadvisor-api/src/v2/api/responses/TeacherWithContactAndRoleResponse.ts
  fictadvisor-api/src/v2/api/responses/TeacherWithSubjectResponse.ts
  fictadvisor-api/src/v2/mappers/StudentMapper.ts
Labels: documentation, back

#123 migration #98: updated events table for new event storing logic
  fictadvisor-api/prisma/migrations/20240113093650_update_of_event_storing/migration.sql
  fictadvisor-api/prisma/schema.prisma
  fictadvisor-api/src/v2/api/controllers/ScheduleController.ts
  fictadvisor-api/src/v2/api/services/ScheduleService.ispec.ts
  fictadvisor-api/src/v2/api/services/ScheduleService.spec.ts
  fictadvisor-api/src/v2/api/services/ScheduleService.ts
  fictadvisor-api/src/v2/database/entities/DbEvent.ts
  fictadvisor-api/src/v2/utils/date/DateModule.ts
  fictadvisor-api/src/v2/utils/date/DateUtils.ts
  fictadvisor-api/src/v2/utils/parser/RozParser.ts
  fictadvisor-api/src/v2/utils/parser/ScheduleParser.ts
Labels: enhancement, migration, back

#142 enhancement #114: added new EventType enum
  fictadvisor-api/src/v2/api/controllers/DisciplineController.ts
  fictadvisor-api/src/v2/api/dtos/AttachLessonDTO.ts
  fictadvisor-api/src/v2/api/dtos/CreateEventDTO.ts
  fictadvisor-api/src/v2/api/dtos/EventTypeEnum.ts
  fictadvisor-api/src/v2/api/dtos/UpdateEventDTO.ts
  fictadvisor-api/src/v2/api/responses/DisciplineTypeResponse.ts
  fictadvisor-api/src/v2/api/responses/EventResponse.ts
  fictadvisor-api/src/v2/api/responses/MainEventInfoResponse.ts
  fictadvisor-api/src/v2/api/services/ScheduleService.ispec.ts
  fictadvisor-api/src/v2/api/services/ScheduleService.ts
  fictadvisor-api/src/v2/mappers/ScheduleMapper.ts
Labels: enhancement, back

#143 bug #22: fixed survey page
  fictadvisor-api/src/v2/api/dtos/QueryAllDisciplineTeacherForPollDTO.ts
  fictadvisor-api/src/v2/api/services/PollService.ts
  fictadvisor-web/src/components/common/ui/form/checkboxes-dropdown/CheckboxesDropdown.stories.tsx
  fictadvisor-web/src/components/common/ui/form/checkboxes-dropdown/CheckboxesDropdown.styles.ts
  fictadvisor-web/src/components/common/ui/form/checkboxes-dropdown/CheckboxesDropdown.tsx
  fictadvisor-web/src/components/pages/search-pages/poll-search-form/PollSearchForm.module.scss
  fictadvisor-web/src/components/pages/search-pages/poll-search-form/PollSearchForm.styles.ts
  fictadvisor-web/src/components/pages/search-pages/poll-search-form/PollSearchForm.tsx
  fictadvisor-web/src/components/pages/search-pages/poll-search-form/constants.ts
  fictadvisor-web/src/components/pages/search-pages/poll-search-form/index.ts
  fictadvisor-web/src/components/pages/search-pages/poll-search-form/types/index.ts
  fictadvisor-web/src/components/pages/search-pages/poll-teachers-page/PollTeacherPage.styles.ts
  fictadvisor-web/src/components/pages/search-pages/poll-teachers-page/PollTeacherPage.tsx
  fictadvisor-web/src/components/pages/search-pages/poll-teachers-page/components/PollTeacherSearchList.styles.ts
  fictadvisor-web/src/components/pages/search-pages/poll-teachers-page/components/PollTeacherSearchList.tsx
  fictadvisor-web/src/lib/api/instance.ts
  fictadvisor-web/src/lib/api/poll/PollAPI.ts
Labels: bug, front, back

#160 feature #35: added admin subject flow
  fictadvisor-web/src/app/admin/subjects/create/page.tsx
  fictadvisor-web/src/app/admin/subjects/edit/[subjectId]/page.tsx
  fictadvisor-web/src/app/admin/subjects/page.tsx
  fictadvisor-web/src/components/pages/admin/admin-subjects/admin-subject-create-page/AdminSubjectCreatePage.styles.ts
  fictadvisor-web/src/components/pages/admin/admin-subjects/admin-subject-create-page/AdminSubjectCreatePage.tsx
  fictadvisor-web/src/components/pages/admin/admin-subjects/admin-subject-create-page/index.ts
  fictadvisor-web/src/components/pages/admin/admin-subjects/admin-subject-edit-page/AdminSubjectEditPage.styles.ts
  fictadvisor-web/src/components/pages/admin/admin-subjects/admin-subject-edit-page/AdminSubjectEditPage.tsx
  fictadvisor-web/src/components/pages/admin/admin-subjects/admin-subject-edit-page/index.ts
  fictadvisor-web/src/components/pages/admin/admin-subjects/admin-subject-search-page/AdminSubjectSearchPage.styles.ts
  fictadvisor-web/src/components/pages/admin/admin-subjects/admin-subject-search-page/AdminSubjectSearchPage.tsx
  fictadvisor-web/src/components/pages/admin/admin-subjects/admin-subject-search-page/components/admin-subject-search/AdminSubjectSearch.styles.ts
  fictadvisor-web/src/components/pages/admin/admin-subjects/admin-subject-search-page/components/admin-subject-search/AdminSubjectSearch.tsx
  fictadvisor-web/src/components/pages/admin/admin-subjects/admin-subject-search-page/components/admin-subject-search/index.ts
  fictadvisor-web/src/components/pages/admin/admin-subjects/admin-subject-search-page/components/admin-subject-table/AdminSubjectTable.styles.ts
  fictadvisor-web/src/components/pages/admin/admin-subjects/admin-subject-search-page/components/admin-subject-table/AdminSubjectTable.tsx
  fictadvisor-web/src/components/pages/admin/admin-subjects/admin-subject-search-page/components/admin-subject-table/index.ts
  fictadvisor-web/src/components/pages/admin/admin-subjects/admin-subject-search-page/index.ts
  fictadvisor-web/src/components/pages/search-pages/subject-search/SubjectSearchPage.tsx
  fictadvisor-web/src/lib/api/subject/SubjectAPI.ts
  fictadvisor-web/src/lib/api/subject/types/GetListOfSubjectsResponse.ts
  fictadvisor-web/src/lib/api/teacher/types/GetTeachersResponse.ts
  fictadvisor-web/src/types/api.ts
Labels: feature, front

#152 feature #11: Added filters by cathedra and role on the teachers page
  fictadvisor-api/src/v2/api/controllers/PollController.ts
  fictadvisor-api/src/v2/api/controllers/SubjectController.ts
  fictadvisor-api/src/v2/api/controllers/TeacherController.ts
  fictadvisor-api/src/v2/api/pipes/QuestionByRoleAndIdPipe.ts
  fictadvisor-api/src/v2/api/responses/DisciplineTeacherResponse.ts
  fictadvisor-api/src/v2/api/responses/DisciplineTeachersResponse.ts
  fictadvisor-api/src/v2/api/responses/PaginatedTeachersResponse.ts
  fictadvisor-api/src/v2/api/responses/PollDisciplineTeachersResponse.ts
  fictadvisor-api/src/v2/api/responses/SubjectWithTeachersResponse.ts
  fictadvisor-api/src/v2/api/responses/TeacherFullResponse.ts
  fictadvisor-api/src/v2/api/responses/TeacherResponse.ts
  fictadvisor-api/src/v2/api/responses/TeacherWithCathedrasResponse.ts
  fictadvisor-api/src/v2/api/responses/TeacherWithContactAndRoleResponse.ts
  fictadvisor-api/src/v2/api/responses/TeacherWithContactsAndRolesResponse.ts
  fictadvisor-api/src/v2/api/responses/TeacherWithContactsFullResponse.ts
  fictadvisor-api/src/v2/api/responses/TeacherWithContactsResponse.ts
  fictadvisor-api/src/v2/api/responses/TeacherWithRatingAndRolesResponse.ts
  fictadvisor-api/src/v2/api/responses/TeacherWithRolesAndCathedrasResponse.ts
  fictadvisor-api/src/v2/api/responses/TeacherWithRolesAndContactsResponse.ts
  fictadvisor-api/src/v2/api/responses/TeacherWithRolesResponse.ts
  fictadvisor-api/src/v2/api/responses/TeacherWithSubjectResponse.ts
  fictadvisor-api/src/v2/api/services/PollService.ts
  fictadvisor-api/src/v2/api/services/ScheduleService.ispec.ts
  fictadvisor-api/src/v2/api/services/SubjectService.ts
  fictadvisor-api/src/v2/api/services/TeacherService.ts
  fictadvisor-api/src/v2/database/entities/DbDiscipline.ts
  fictadvisor-api/src/v2/database/entities/DbDisciplineTeacher.ts
  fictadvisor-api/src/v2/database/entities/DbTeacher.ts
  fictadvisor-api/src/v2/database/repositories/DisciplineRepository.ts
  fictadvisor-api/src/v2/database/repositories/DisciplineTeacherRepository.ts
  fictadvisor-api/src/v2/database/repositories/TeacherRepository.ts
  fictadvisor-api/src/v2/mappers/DisciplineMapper.ts
  fictadvisor-api/src/v2/mappers/DisciplineTeacherMapper.ts
  fictadvisor-api/src/v2/mappers/TeacherMapper.ts
  fictadvisor-web/src/components/common/ui/cards/card-roles/CardRoles.module.scss
  fictadvisor-web/src/components/common/ui/cards/card-roles/CardRoles.styles.ts
  fictadvisor-web/src/components/common/ui/cards/card-roles/CardRoles.tsx
  fictadvisor-web/src/components/common/ui/cards/floating-card/FloatingCard.tsx
  fictadvisor-web/src/components/common/ui/cards/personal-teacher-card/PersonalTeacherCard.tsx
  fictadvisor-web/src/components/common/ui/cards/poll-teacher-card/PollTeacherCard.module.scss
  fictadvisor-web/src/components/common/ui/cards/poll-teacher-card/PollTeacherCard.tsx
  fictadvisor-web/src/components/common/ui/cards/teacher-card/TeacherCard.styles.ts
  fictadvisor-web/src/components/common/ui/cards/teacher-card/TeacherCard.tsx
  fictadvisor-web/src/components/pages/admin/admin-subjects/admin-subject-search-page/components/admin-subject-search/AdminSubjectSearch.tsx
  fictadvisor-web/src/components/pages/search-pages/poll-teachers-page/components/PollTeacherSearchList.tsx
  fictadvisor-web/src/components/pages/search-pages/search-form/SearchForm.module.scss
  fictadvisor-web/src/components/pages/search-pages/search-form/SearchForm.styles.ts
  fictadvisor-web/src/components/pages/search-pages/search-form/SearchForm.tsx
  fictadvisor-web/src/components/pages/search-pages/search-form/constants.ts
  fictadvisor-web/src/components/pages/search-pages/search-form/types/index.ts
  fictadvisor-web/src/components/pages/search-pages/subject-search/SubjectSearchPage.tsx
  fictadvisor-web/src/components/pages/search-pages/subject-teacher-search/components/SubjectTeacherSearchList.tsx
  fictadvisor-web/src/components/pages/search-pages/teacher-search/TeacherSearchPage.tsx
  fictadvisor-web/src/components/pages/search-pages/teacher-search/components/TeacherSearchList.tsx
  fictadvisor-web/src/components/pages/search-pages/teacher-search/constants/index.ts
  fictadvisor-web/src/lib/api/cathera/CathedraAPI.ts
  fictadvisor-web/src/lib/api/cathera/types/GetAllResponse.ts
  fictadvisor-web/src/lib/api/subject/SubjectAPI.ts
  fictadvisor-web/src/types/teacher.ts
Labels: feature, front, back

#168 bug #145: reset password is not working
  fictadvisor-web/src/app/password-recovery/[token]/page.tsx
  fictadvisor-web/src/components/pages/account-page/components/security-tab/components/change-password-form/ChangePasswordForm.tsx
  fictadvisor-web/src/components/pages/password-recovery/create-password-page/CreatePasswordPage.tsx
  fictadvisor-web/src/components/pages/password-recovery/create-password-page/components/create-password-form/CreatePasswordForm.tsx
  fictadvisor-web/src/components/pages/password-recovery/validation/changePasswordValidationSchema.ts
  fictadvisor-web/src/components/pages/password-recovery/validation/createPasswordValidationSchema.ts
  fictadvisor-web/src/components/pages/register/register-page/components/register-form/validation/index.ts
Labels: bug, front

#153 bug #136: fixed group management buttons on desktop
  fictadvisor-web/src/components/pages/account-page/components/group-tab/GroupTab.tsx
  fictadvisor-web/src/components/pages/account-page/components/group-tab/components/table/student-table/StudentsTable.styles.ts
  fictadvisor-web/src/components/pages/account-page/components/group-tab/components/table/student-table/StudentsTable.tsx
  fictadvisor-web/src/components/pages/account-page/components/group-tab/components/table/types/index.ts
Labels: bug, front

#163 migration #113: added division field to cathedras table
  fictadvisor-api/prisma/migrations/20240122125814_add_division_to_cathedra/migration.sql
  fictadvisor-api/prisma/schema.prisma
  fictadvisor-api/src/v2/api/dtos/CreateCathedraDTO.ts
  fictadvisor-api/src/v2/api/dtos/UpdateCathedraDTO.ts
  fictadvisor-api/src/v2/api/responses/CathedraResponse.ts
  fictadvisor-api/src/v2/database/entities/DbCathedra.ts
  fictadvisor-api/src/v2/mappers/CathedraMapper.ts
  fictadvisor-api/src/v2/mappers/DisciplineTeacherMapper.ts
  fictadvisor-api/src/v2/mappers/TeacherMapper.ts
Labels: migration

#171 bug #15: Fix remove social media link
  fictadvisor-web/src/components/pages/account-page/components/general-tab/components/contacts-block/components/ContactItem.tsx
Labels: bug

#179 bug #147: aligned change button relatively to its window
  fictadvisor-web/src/components/pages/account-page/components/group-tab/components/table/student-table/components/editing-column/EditingColumn.styles.ts
Labels: bug

#183 bug #176: fixed telegram auth bug
  fictadvisor-web/src/app/layout.tsx
  fictadvisor-web/src/lib/services/telegram/TelegramService.ts
Labels: bug

#182 bug #130: fixed a bug with the toast message about unselected disciplines on the survey page
  fictadvisor-api/src/v2/api/services/PollService.ts
Labels: bug, back

#181 bug #156: reset complaint form
  fictadvisor-web/src/components/pages/personal-teacher-page/personal-teacher-tabs/components/complaint-popup/ComplaintPopup.tsx
Labels: bug, front

#186 migration #107: Added table for storing texts
  fictadvisor-api/prisma/migrations/20240127110546_main_page/migration.sql
  fictadvisor-api/prisma/schema.prisma
Labels: migration, back

#164 feature #151: saved homework in pairs
  fictadvisor-api/src/v2/api/controllers/ScheduleController.ts
  fictadvisor-api/src/v2/api/dtos/UpdateEventDTO.ts
  fictadvisor-api/src/v2/api/responses/EventInfoResponse.ts
  fictadvisor-api/src/v2/api/responses/EventResponse.ts
  fictadvisor-api/src/v2/api/services/ScheduleService.ts
  fictadvisor-api/src/v2/mappers/ScheduleMapper.ts
Labels: feature, back

#199 fix #198: fixed registration flow
  fictadvisor-web/src/app/register/email-verification/[token]/page.tsx
  fictadvisor-web/src/components/pages/register/verify-email-token-page/VerifyEmailTokenPage.tsx
Labels: bug
