Repository fictadvisor/fictadvisor, pull requests merged in 2024-02, with the labels that each got.

#192 feature #158: separated TextArea from Formik
  fictadvisor-web/src/components/common/ui/form/checkboxes-dropdown/CheckboxesDropdown.stories.tsx
  fictadvisor-web/src/components/common/ui/form/text-area-mui/TextArea.stories.tsx
  fictadvisor-web/src/components/common/ui/form/text-area-mui/TextArea.tsx
  fictadvisor-web/src/components/common/ui/form/with-formik/text-area/FormikTextArea.tsx
  fictadvisor-web/src/components/common/ui/form/with-formik/text-area/index.ts
  fictadvisor-web/src/components/common/ui/form/with-formik/text-area/types/index.ts
  fictadvisor-web/src/components/pages/personal-teacher-page/personal-teacher-tabs/components/complaint-popup/components/ComplaintPopupContent.tsx
  fictadvisor-web/src/components/pages/poll-page/components/single-question/SingleQuestion.tsx
Labels: feature, front

#194 bug #190: changed disciplineType to eventType
  fictadvisor-api/src/v2/api/responses/DisciplineTypeResponse.ts
  fictadvisor-api/src/v2/api/responses/MainEventInfoResponse.ts
  fictadvisor-api/src/v2/mappers/ScheduleMapper.ts
  fictadvisor-web/src/components/pages/schedule-page/schedule-event-edit-section/schedule-form/ScheduleEventForm.tsx
  fictadvisor-web/src/components/pages/schedule-page/schedule-event-edit-section/schedule-form/constants/index.ts
  fictadvisor-web/src/components/pages/schedule-page/schedule-event-edit-section/schedule-form/validation/index.ts
  fictadvisor-web/src/components/pages/schedule-page/schedule-event-edit-section/schedule-info-card/ScheduleInfoCard.tsx
  fictadvisor-web/src/components/pages/schedule-page/schedule-event-edit-section/utils/prepareData.ts
  fictadvisor-web/src/components/pages/schedule-page/schedule-section/ScheduleSectionMobile.tsx
  fictadvisor-web/src/components/pages/schedule-page/schedule-section/components/schedule/Schedule.tsx
  fictadvisor-web/src/components/pages/schedule-page/schedule-section/components/schedule/components/schedule-column/components/schedule-card/cards/Cards.styles.ts
  fictadvisor-web/src/components/pages/schedule-page/schedule-section/components/schedule/components/schedule-column/components/schedule-card/cards/ScheduleEvent.tsx
  fictadvisor-web/src/components/pages/schedule-page/schedule-section/components/schedule/components/schedule-column/components/schedule-card/cards/ScheduleEvents.tsx
  fictadvisor-web/src/lib/api/schedule/ScheduleAPI.ts
  fictadvisor-web/src/lib/api/schedule/types/DetailedEventBody.ts
  fictadvisor-web/src/lib/api/schedule/types/PatchEventBody.ts
  fictadvisor-web/src/store/schedule/useSchedule.ts
  fictadvisor-web/src/types/schedule.ts
Labels: bug, front, back

#211 bugfix #204: fixed bugs in new schedule logic
  fictadvisor-api/src/v2/api/controllers/ScheduleController.ts
  fictadvisor-api/src/v2/api/services/ScheduleService.ts
Labels: bug

#223 bugfix #221: change timezone on schedule
  fictadvisor-web/src/store/schedule/useSchedule.ts
Labels: bug, front

#227 bug #210: fixed 'download more' button
  fictadvisor-web/src/components/pages/search-pages/teacher-search/TeacherSearchPage.tsx
  fictadvisor-web/src/components/pages/search-pages/teacher-search/components/TeacherSearchList.tsx
Labels: bug, front

#203 bug #148: align group students
  fictadvisor-web/src/components/pages/account-page/components/group-tab/components/table/student-table/components/editing-column/EditingColumn.styles.ts
Labels: bug, front

#222 enhancement #220: added an ability to create discipline teachers with…
  fictadvisor-api/src/v2/api/controllers/DisciplineController.ts
  fictadvisor-api/src/v2/api/dtos/CreateDisciplineDTO.ts
  fictadvisor-api/src/v2/api/services/DisciplineService.ts
  fictadvisor-api/src/v2/mappers/DisciplineMapper.ts
  fictadvisor-api/src/v2/utils/GLOBALS.ts
Labels: enhancement, back

#234 bug #231: highlight current tab
  fictadvisor-web/src/components/common/layout/header/components/mobile-header/components/drawer/Drawer.tsx
Labels: bug, front

#237 bugfix #229: fixed roz kpi parser
  fictadvisor-api/src/v2/utils/parser/RozParser.ts
Labels: bug, back

#236 enhancement #235: improved get all questions endpoint
  fictadvisor-api/src/v2/api/dtos/SortQAQParam.ts
Labels: enhancement, back

#241 bug #196: unified validation reaction
  fictadvisor-web/src/components/pages/register/register-page/components/register-form/RegisterForm.tsx
Labels: bug, front

#244 bugfix #206: changed placeholders in password recovery form
  fictadvisor-web/src/components/pages/password-recovery/create-password-page/components/create-password-form/CreatePasswordForm.tsx
Labels: bug

#200 bug #193: fixed teachers fetching second request
  fictadvisor-web/src/components/pages/search-pages/teacher-search/TeacherSearchPage.tsx
Labels: bug, front

#246 bugfix #213: fixed permissions for default students
  fictadvisor-api/src/v2/api/services/GroupService.ts
Labels: bug, back

#180 bug #33: fixed button and event form overlaying over drawer
  fictadvisor-web/src/components/common/layout/header/components/mobile-header/components/drawer/Drawer.styles.ts
  fictadvisor-web/src/components/common/layout/page-layout/PageLayout.module.scss
Labels: bug, front

#243 bug #242: fixed titles on home, schedule, account pages
  fictadvisor-web/src/app/account/page.tsx
  fictadvisor-web/src/app/page.tsx
  fictadvisor-web/src/app/schedule/page.tsx
Labels: bug, front

#256 feature #177: restricted access to the teachers in poll
  fictadvisor-api/src/v2/api/services/ScheduleService.ispec.ts
  fictadvisor-api/src/v2/api/services/UserService.ispec.ts
  fictadvisor-api/src/v2/api/services/UserService.ts
  fictadvisor-api/src/v2/modules/UserModule.ts
Labels: feature, back

#262 enhancement #253: fix admin answers review
  fictadvisor-web/src/components/pages/admin/admin-comments/components/admin-comments-table/CommentsTable.tsx
Labels: enhancement, front

#264 bug #63: fixed label colors in event info card
  fictadvisor-web/src/components/pages/schedule-page/schedule-event-edit-section/schedule-info-card/ScheduleInfoCard.tsx
Labels: bug

#265 enhancement #32: added opengraph tags
  fictadvisor-web/src/app/(admission)/_contract-admin/page.tsx
  fictadvisor-web/src/app/(admission)/_entrant-admin/page.tsx
  fictadvisor-web/src/app/(admission)/_entrant-dashboard/page.tsx
  fictadvisor-web/src/app/about/page.tsx
  fictadvisor-web/src/app/account/page.tsx
  fictadvisor-web/src/app/discipline/page.tsx
  fictadvisor-web/src/app/login/page.tsx
  fictadvisor-web/src/app/not-found.tsx
  fictadvisor-web/src/app/opengraph-image.jpg
  fictadvisor-web/src/app/page.tsx
  fictadvisor-web/src/app/poll/[disciplineTeacherId]/page.tsx
  fictadvisor-web/src/app/poll/opengraph-image.jpg
  fictadvisor-web/src/app/poll/page.tsx
  fictadvisor-web/src/app/privacy/page.tsx
  fictadvisor-web/src/app/register/page.tsx
  fictadvisor-web/src/app/schedule/opengraph-image.jpg
  fictadvisor-web/src/app/schedule/page.tsx
  fictadvisor-web/src/app/subjects/[subjectId]/teachers/page.tsx
  fictadvisor-web/src/app/subjects/opengraph-image.jpg
  fictadvisor-web/src/app/subjects/page.tsx
  fictadvisor-web/src/app/teachers/[teacherId]/opengraph-image.jpg
  fictadvisor-web/src/app/teachers/opengraph-image.jpg
  fictadvisor-web/src/app/teachers/page.tsx
Labels: enhancement, SEO

#268 bug #249: inputs placeholders text in user create admin tab
  fictadvisor-web/src/components/common/ui/form/input-mui/Input.styles.ts
  fictadvisor-web/src/components/pages/schedule-page/schedule-event-edit-section/schedule-form/ScheduleEventForm.tsx
Labels: bug, front

#267 bug #89: fixed admin panel links
  fictadvisor-web/src/components/common/layout/admin-panel/constants/index.tsx
Labels: bug
