Repository fictadvisor/fictadvisor, pull requests merged in 2024-10, with the labels that each got.

#528 enhancement #513: refactored auth controller
  fictadvisor-api/src/v2/api/controllers/AuthController.ts
  fictadvisor-api/src/v2/utils/documentation/auth/checkCaptain.ts
  fictadvisor-api/src/v2/utils/documentation/auth/checkRegisterTelegram.ts
  fictadvisor-api/src/v2/utils/documentation/auth/checkResetToken.ts
  fictadvisor-api/src/v2/utils/documentation/auth/forgotPassword.ts
  fictadvisor-api/src/v2/utils/documentation/auth/getMe.ts
  fictadvisor-api/src/v2/utils/documentation/auth/index.ts
  fictadvisor-api/src/v2/utils/documentation/auth/login.ts
  fictadvisor-api/src/v2/utils/documentation/auth/loginTelegram.ts
  fictadvisor-api/src/v2/utils/documentation/auth/refresh.ts
  fictadvisor-api/src/v2/utils/documentation/auth/register.ts
  fictadvisor-api/src/v2/utils/documentation/auth/registerTelegram.ts
  fictadvisor-api/src/v2/utils/documentation/auth/requestEmailVerification.ts
  fictadvisor-api/src/v2/utils/documentation/auth/resetPassword.ts
  fictadvisor-api/src/v2/utils/documentation/auth/updatePassword.ts
  fictadvisor-api/src/v2/utils/documentation/auth/verifyEmail.ts
  fictadvisor-api/src/v2/utils/documentation/auth/verifyExistsByUnique.ts
  fictadvisor-api/src/v2/utils/documentation/decorators.ts
  utils/src/requests/ForgotPasswordDTO.ts
  utils/src/requests/IdentityQueryDTO.ts
  utils/src/requests/LoginDTO.ts
  utils/src/requests/RegisterTelegramDTO.ts
  utils/src/requests/ResetPasswordDTO.ts
  utils/src/requests/StudentDTO.ts
  utils/src/requests/UserDTO.ts
  utils/src/requests/VerificationEmailDTO.ts
Labels: documentation, refactoring, back

#529 enhancement #512: refactored cathedra controller
  fictadvisor-api/src/v2/api/controllers/CathedraController.ts
  fictadvisor-api/src/v2/utils/documentation/cathedra/create.ts
  fictadvisor-api/src/v2/utils/documentation/cathedra/delete.ts
  fictadvisor-api/src/v2/utils/documentation/cathedra/getAll.ts
  fictadvisor-api/src/v2/utils/documentation/cathedra/getAllDivisions.ts
  fictadvisor-api/src/v2/utils/documentation/cathedra/getById.ts
  fictadvisor-api/src/v2/utils/documentation/cathedra/index.ts
  fictadvisor-api/src/v2/utils/documentation/cathedra/update.ts
  utils/src/requests/CreateCathedraDTO.ts
  utils/src/requests/QueryAllCathedrasDTO.ts
  utils/src/requests/UpdateCathedraDTO.ts
Labels: documentation, refactoring, back

#535 enhancement #534: Added id param
  fictadvisor-api/.env.example
  fictadvisor-api/src/main.ts
  fictadvisor-api/src/v2/api/services/TeacherService.ts
  fictadvisor-api/src/v2/telegram/TelegramAPI.ts
Labels: enhancement, back

#536 feature #530: admin middleware access
  fictadvisor-api/src/v2/api/controllers/PermissionController.ts
  fictadvisor-web/src/app/(main)/account/components/group-tab/GroupTab.tsx
  fictadvisor-web/src/app/(main)/schedule/schedule-page/calendar-section/CalendarSection.tsx
  fictadvisor-web/src/app/(main)/schedule/schedule-page/schedule-event-edit-section/schedule-info-card/ScheduleInfoCard.tsx
  fictadvisor-web/src/app/admin/comments/layout.tsx
  fictadvisor-web/src/app/admin/departments/layout.tsx
  fictadvisor-web/src/app/admin/disciplines/layout.tsx
  fictadvisor-web/src/app/admin/groups/layout.tsx
  fictadvisor-web/src/app/admin/main/layout.tsx
  fictadvisor-web/src/app/admin/questions/layout.tsx
  fictadvisor-web/src/app/admin/roles/[roleId]/layout.tsx
  fictadvisor-web/src/app/admin/roles/layout.tsx
  fictadvisor-web/src/app/admin/students/layout.tsx
  fictadvisor-web/src/app/admin/subjects/layout.tsx
  fictadvisor-web/src/app/admin/teachers/layout.tsx
  fictadvisor-web/src/app/admin/users/layout.tsx
  fictadvisor-web/src/components/common/layout/admin-panel-access-layout/AdminPanelAccessLayout.tsx
  fictadvisor-web/src/components/common/layout/admin-panel-layout/AdminPanelLayout.tsx
  fictadvisor-web/src/lib/services/group/GroupService.ts
  fictadvisor-web/src/lib/services/permission/PermissionService.ts
  fictadvisor-web/src/lib/services/permission/types/index.ts
  fictadvisor-web/src/lib/services/permission/utils/createPermissionRequest.ts
  fictadvisor-web/src/middleware.ts
  fictadvisor-web/src/types/adminPermissions.ts
  utils/src/requests/CheckPermissionsDTO.ts
Labels: feature, front

#537 refactor: СheckPermissionsRes and PermissionApi
  fictadvisor-api/src/v2/api/controllers/PermissionController.ts
  fictadvisor-web/src/app/(main)/account/components/group-tab/components/table/student-table/components/editing-column/EditingColumn.tsx
  fictadvisor-web/src/app/(main)/account/components/group-tab/components/table/student-table/components/mobile-dropdown/MobileDropdown.tsx
  fictadvisor-web/src/app/(main)/account/components/group-tab/components/table/types/index.ts
  fictadvisor-web/src/app/(main)/schedule/schedule-page/calendar-section/CalendarSection.tsx
  fictadvisor-web/src/app/(main)/schedule/schedule-page/schedule-event-edit-section/schedule-info-card/ScheduleInfoCard.tsx
  fictadvisor-web/src/lib/api/permission/PermissionApi.ts
  fictadvisor-web/src/lib/services/group/GroupService.ts
  fictadvisor-web/src/lib/services/permission/PermissionService.ts
  fictadvisor-web/src/lib/services/permission/types/index.ts
  fictadvisor-web/src/middleware.ts
  utils/src/responses/CheckPermissionsResponse.ts
Labels: bug, back
