Repository fictadvisor/fictadvisor, pull requests merged in 2024-07, with the labels that each got.

#396 enhancement #62: implemented integration tests for updateEvent method
  fictadvisor-api/src/v2/api/controllers/ScheduleController.ts
  fictadvisor-api/src/v2/api/services/ScheduleService.ispec.ts
  fictadvisor-api/src/v2/api/services/ScheduleService.ts
  utils/src/requests/UpdateEventDTO.ts
Labels: enhancement, back

#398 bug #336: rearranged some if statements to make right logic
  fictadvisor-web/src/app/admin/students/edit/[studentId]/page.tsx
Labels: bug

#407 bug #402 fixed doubled footer on survey page
  .gitignore
  fictadvisor-web/src/app/(main)/(search-pages)/poll/[disciplineTeacherId]/layout.tsx
Labels: bug

#400 bug #362 fixed time in the time bar on the "Schedule" page
  fictadvisor-web/src/app/(main)/schedule/schedule-page/schedule-section/components/schedule/components/schedule-line/ScheduleLine.tsx
  fictadvisor-web/src/store/schedule/useSchedule.ts
Labels: bug

#428 bug #427: fixed bug in email service
  fictadvisor-api/src/v2/api/services/EmailService.ts
Labels: bug, back
