Repository fictadvisor/fictadvisor, pull requests merged in 2025-01, with the labels that each got.

#592 bug #590: fixed design inconsistencies
  fictadvisor-web/src/app/(main)/(search-pages)/poll/PollTeacherPage.styles.ts
  fictadvisor-web/src/app/(main)/schedule/schedule-page/calendar-section/components/date-picker/DatePicker.tsx
  fictadvisor-web/src/styles/typography.scss
Labels: bug, front

#523 enhancement #504: Refactored Schedule controller
  fictadvisor-api/src/v2/api/controllers/ScheduleController.ts
  fictadvisor-api/src/v2/api/pipes/EventPipe.ts
  fictadvisor-api/src/v2/api/services/DisciplineTeacherService.ts
  fictadvisor-api/src/v2/api/services/PermissionService.ts
  fictadvisor-api/src/v2/api/services/ScheduleService.ispec.ts
  fictadvisor-api/src/v2/api/services/ScheduleService.spec.ts
  fictadvisor-api/src/v2/api/services/ScheduleService.ts
  fictadvisor-api/src/v2/api/services/UserService.ts
  fictadvisor-api/src/v2/database/repositories/EventRepository.ts
  fictadvisor-api/src/v2/mappers/ScheduleMapper.ts
  fictadvisor-api/src/v2/security/multiple-access-guard/MultipleAccessGuard.ts
  fictadvisor-api/src/v2/security/permission-guard/PermissionGuard.ts
  fictadvisor-api/src/v2/utils/ArrayUtil.spec.ts
  fictadvisor-api/src/v2/utils/ArrayUtil.ts
  fictadvisor-api/src/v2/utils/date/DateService.ts
  fictadvisor-api/src/v2/utils/documentation/schedule/createEvent.ts
  fictadvisor-api/src/v2/utils/documentation/schedule/createFacultyEvent.ts
  fictadvisor-api/src/v2/utils/documentation/schedule/deleteEvent.ts
  fictadvisor-api/src/v2/utils/documentation/schedule/getEvent.ts
  fictadvisor-api/src/v2/utils/documentation/schedule/getGeneralEvents.ts
  fictadvisor-api/src/v2/utils/documentation/schedule/getGroupEvents.ts
  fictadvisor-api/src/v2/utils/documentation/schedule/getGroupEventsByDay.ts
  fictadvisor-api/src/v2/utils/documentation/schedule/getGroupEventsByFortnight.ts
  fictadvisor-api/src/v2/utils/documentation/schedule/getGroupEventsByWeek.ts
  fictadvisor-api/src/v2/utils/documentation/schedule/index.ts
  fictadvisor-api/src/v2/utils/documentation/schedule/parse.ts
  fictadvisor-api/src/v2/utils/documentation/schedule/updateEvent.ts
  fictadvisor-web/src/app/(main)/schedule/schedule-page/schedule-event-edit-section/ScheduleEventEdit.tsx
  fictadvisor-web/src/lib/api/schedule/ScheduleAPI.ts
  fictadvisor-web/src/lib/api/schedule/types/EventsResponse.ts
  fictadvisor-web/src/lib/api/schedule/types/GeneralEventsResponse.ts
  fictadvisor-web/src/lib/api/schedule/types/MainEventInfoResponse.ts
  turbo.json
  utils/src/enums/other/ParserTypeEnum.ts
  utils/src/enums/other/index.ts
  utils/src/requests/AttachLessonDTO.ts
  utils/src/requests/CreateEventDTO.ts
  utils/src/requests/CreateFacultyEventDTO.ts
  utils/src/requests/EventFiltrationDTO.ts
  utils/src/requests/GeneralEventFiltrationDTO.ts
  utils/src/requests/ParseScheduleQueryDTO.ts
  utils/src/requests/UpdateEventDTO.ts
  utils/src/requests/index.ts
  utils/src/responses/EventInfoResponse.ts
  utils/src/responses/EventResponse.ts
  utils/src/responses/EventsResponse.ts
  utils/src/responses/ShortEventResponse.ts
  utils/src/responses/TelegramGeneralEventInfoResponse.ts
  utils/src/responses/index.ts
Labels: documentation, refactoring, back

#598 enhancement: added group list generation in xlsx format
  fictadvisor-api/package.json
  fictadvisor-api/src/v2/utils/files/FileService.ts
  yarn.lock
Labels: enhancement, back

#619 bugfix/schedule-requests
  fictadvisor-web/src/app/(main)/schedule/schedule-page/schedule-section/components/schedule-header/ScheduleHeader.tsx
  fictadvisor-web/src/store/schedule/useSchedule.ts
Labels: bug, front
